unit TestuConfigManager;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, Forms, uConfigManager, System.SysUtils,
  System.IniFiles, Windows;

type
  // Test methods for class TConfigManager

  TestTConfigManager = class(TTestCase)
  strict private
    FConfigManager: TConfigManager;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoadSettings;
    procedure TestSetRelease;
    procedure TestSetBuild;
  end;

implementation

procedure TestTConfigManager.SetUp;
begin
  CopyFile(PChar(ExtractFilePath(Application.ExeName) + 'testconfig.ini'),
           PChar(ExtractFilePath(Application.ExeName) + 'testconfig1.ini'),
           false);
  FConfigManager := TConfigManager.Create(ExtractFilePath(Application.ExeName) +
                                          'testconfig1.ini');
end;

procedure TestTConfigManager.TearDown;
begin
  DeleteFile(PChar(ExtractFilePath(Application.ExeName) + 'testconfig1.ini'));
  FreeAndNil(FConfigManager);
end;

procedure TestTConfigManager.TestLoadSettings;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FConfigManager.LoadSettings;
  ReturnValue := ReturnValue and
                 (length(FConfigManager.Programs) = 2) and
                 (FConfigManager.Programs[0].s_SectionName = 'PROGRAM1') and
                 (FConfigManager.Programs[1].s_SectionName = 'PROGRAM2') and
                 (FConfigManager.Programs[0].s_ProgramName = 'MONITORING') and
                 (FConfigManager.Programs[1].s_ProgramName = 'LOGISTIC') and
                 (FConfigManager.Programs[0].s_SourceURL = 'http://test.ils-glonass.ru:8080/job/ILS Web Project/job/ILSWebLogistic_Release') and
                 (FConfigManager.Programs[1].s_SourceURL = 'http://test.ils-glonass.ru:8080/job/ILS Web Project/job/ILSWebLogistic_Release') and
                 (FConfigManager.Programs[0].s_SourceUser = 'DStepanov') and
                 (FConfigManager.Programs[1].s_SourceUser = 'DStepanov') and
                 (FConfigManager.Programs[0].s_SourcePass = 'DS123') and
                 (FConfigManager.Programs[1].s_SourcePass = 'DS123') and
                 (FConfigManager.Programs[0].s_SourceReleaseDir = 'release/') and
                 (FConfigManager.Programs[1].s_SourceReleaseDir = 'release/') and
                 (FConfigManager.Programs[0].s_DestinationDir = '') and
                 (FConfigManager.Programs[1].s_DestinationDir = 'C:\1') and
                 (FConfigManager.Programs[0].Database.s_DatabaseServer = '1') and
                 (FConfigManager.Programs[1].Database.s_DatabaseServer = 'SCIV-PC') and
                 (FConfigManager.Programs[0].Database.s_DatabaseUser = 'sa') and
                 (FConfigManager.Programs[1].Database.s_DatabaseUser = 'sa') and
                 (FConfigManager.Programs[0].Database.s_DatabasePass = '123') and
                 (FConfigManager.Programs[1].Database.s_DatabasePass = 'SAsql123') and
                 (FConfigManager.Programs[0].Database.s_DatabaseName = '1') and
                 (FConfigManager.Programs[1].Database.s_DatabaseName = '2') and
                 (FConfigManager.Programs[0].sl_ProgramFiles.Count = 2) and
                 (FConfigManager.Programs[1].sl_ProgramFiles.Count = 2) and
                 (FConfigManager.Programs[0].sl_ProgramServices.Count = 3) and
                 (FConfigManager.Programs[1].sl_ProgramServices.Count = 2) and
                 (FConfigManager.Programs[0].sl_ProgramTasks.Count = 1) and
                 (FConfigManager.Programs[1].sl_ProgramTasks.Count = 2) and
                 (FConfigManager.Programs[0].s_CurrentBuild = '0') and
                 (FConfigManager.Programs[1].s_CurrentBuild = '1') and
                  not FConfigManager.Programs[1].b_IsDeploy and
                  FConfigManager.Programs[1].b_IsZipPacked and
                 (FConfigManager.GlobalSettings.s_JenkinsUser = 'DStepanov') and
                 (FConfigManager.GlobalSettings.s_JenkinsPass = 'DS123') and
                 (FConfigManager.GlobalSettings.s_DatabaseServer = 'SCIV-PC') and
                 (FConfigManager.GlobalSettings.s_DatabaseUser = 'sa') and
                 (FConfigManager.GlobalSettings.s_DatabasePass = 'SAsql123') and
                 (FConfigManager.GlobalSettings.s_DBUpdaterDir = 'd:\DBUpdater\MonitoringUpdater.exe') and
                 (FConfigManager.GlobalSettings.s_CurrentRelease = '7.1.1') and
                 (FConfigManager.GlobalSettings.b_UseStableBuilds = true) and
                 (FConfigManager.GlobalSettings.i_CheckPeriod = 0) and
                 (FConfigManager.GlobalSettings.s_TempDir = ExtractFilePath(Application.ExeName) + 'TEMP') and
                 (FConfigManager.GlobalSettings.b_IsMaster = true);
  CheckTrue(ReturnValue);
end;

procedure TestTConfigManager.TestSetRelease;
var
  AReleaseNumber: string;
begin
  FConfigManager.LoadSettings;
  FConfigManager.SetRelease('7.5.5');
  FConfigManager.LoadSettings;
  CheckEquals('7.5.5', FConfigManager.GlobalSettings.s_CurrentRelease, '');
end;

procedure TestTConfigManager.TestSetBuild;
var
  ABuildNumber: string;
  AProgram: TProgramSettings;
begin
  FConfigManager.LoadSettings;
  FConfigManager.SetBuild(FConfigManager.Programs[0], '1000');
  FConfigManager.LoadSettings;
  CheckEquals('1000', FConfigManager.Programs[0].s_CurrentBuild, '');
end;

initialization
  RegisterTest(TestTConfigManager.Suite);
end.

