unit TestuAutodeployService;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Vcl.Graphics, Vcl.SvcMgr, Winapi.Windows,
  uConfigManager, uLogManager, Vcl.Controls, Vcl.Dialogs, Winapi.Messages,
  uDeployManager, uAutodeployService, System.Classes;

type
  // Test methods for class TILSAutodeployService

  TestTILSAutodeployService = class(TTestCase)
  strict private
    FILSAutodeployService: TILSAutodeployService;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
{    procedure TestServiceStart;
    procedure TestServiceStop;  }
    procedure TestServiceBeforeInstall;
    procedure TestServiceBeforeUninstall;
    procedure TestGetServiceInstance;
  end;

implementation

procedure TestTILSAutodeployService.SetUp;
begin
  FILSAutodeployService := TILSAutodeployService.Create(nil);
end;

procedure TestTILSAutodeployService.TearDown;
begin
  FILSAutodeployService.Free;
  FILSAutodeployService := nil;
end;

{
procedure TestTILSAutodeployService.TestServiceStart;
var
  Started: Boolean;
  Sender: TService;
begin
  // TODO: Setup method call parameters
  FILSAutodeployService.ServiceStart(Sender, Started);
  // TODO: Validate method results
end;

procedure TestTILSAutodeployService.TestServiceStop;
var
  Stopped: Boolean;
  Sender: TService;
begin
  // TODO: Setup method call parameters
  FILSAutodeployService.ServiceStop(Sender, Stopped);
  // TODO: Validate method results
end;                 }

procedure TestTILSAutodeployService.TestServiceBeforeInstall;
begin
  FILSAutodeployService.ServiceBeforeInstall(nil);
  CheckEquals('ILSAutodeployService', FILSAutodeployService.Name);
end;

procedure TestTILSAutodeployService.TestServiceBeforeUninstall;
begin
  FILSAutodeployService.ServiceBeforeUninstall(nil);
  CheckEquals('ILSAutodeployService', FILSAutodeployService.Name);
end;

procedure TestTILSAutodeployService.TestGetServiceInstance;
var
  ReturnValue: string;
begin
  FILSAutodeployService.Name := 'Service_Test';
  ReturnValue := FILSAutodeployService.GetServiceInstance;
  CheckEquals('Test', ReturnValue, '');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTILSAutodeployService.Suite);
end.

